### ISSUE TITLE
lifelongmapping

### ISSUE THREAD

**Issue by Quitino** [zhouyong1234/Laser-SLAM-Course#1]
博主您好，请问 第八讲 lifelongmapping  有demo 代码吗？可以分享学习一下吗？谢谢博主。fb_941219@163.com ,， 感谢博主。

**Comment by zhouyong1234** [comment]
课程没有提供代码，可以看下这个：https://github.com/gisbi-kim/lt-mapper

**Comment by Quitino** [comment]
感谢博主回复，这个我看过，好像没涉及到 pose_graph 的稀疏化，最近主要是再看这方面的，有篇高仙的论文也是这个思想。感谢博主的回复。

**Comment by Quitino** [comment]
博主再请教您一个问题，在稠密近似（第八节PPT P22）时，有复合边：

```
e23_ = edge_composition(e29,e93)
e23 = edge_combine(e23_, e23)
e34_ = edge_composition(e39, e94)
e34 = edge_combie(e34_, e34)
```

照理来说， e23_ 为边缘化后的信息，它已经包含了 e23 信息了呀，为什么还需要组合？ 感谢博主。

**Comment by zhouyong1234** [comment]
用VIO课程里的话来解释吧
![2022-07-19 17-42-14屏幕截图](https://user-images.githubusercontent.com/46642375/179720315-0dfee3f2-6f5b-4675-8216-8cd82a80f509.png)
这里的e23_就是丢弃变量x9所携带的信息，与e23组合就是将丢弃变量所携带的信息传递给剩余变量
![2022-07-19 17-46-19屏幕截图](https://user-images.githubusercontent.com/46642375/179721158-b956c7e3-cf2a-4b3a-96b3-3b25174ce5a2.png)
用图表示就是信息矩阵的叠加

**Comment by Quitino** [comment]
感谢博主的回复。不过感觉还是有疑问：这里的 $\Lambda _{new}$ 的合成是因为有新的观测加入，而稀疏化是在边缘化之后，新观测加入之前进行的，也就是对这里的 $\Lambda$ 进行稀疏化：

![image](https://user-images.githubusercontent.com/38552528/179762362-22de5078-0706-47f9-88cb-22e9a47bfe8a.png)

**Comment by zhouyong1234** [comment]
上面的合成是边缘化+新的约束，加2和7的约束是因为原有的变量2和新的变量7形成约束，而下面的2和3本来就存在约束，这里的2和3的约束和上面的2和7的约束是同一类型的约束，只不过3是原来就存在的，7是新加入的

**Comment by Quitino** [comment]
是我搞错了，我之前参考的[这篇文章](https://xiaotaoguo.com/p/lidarslam-lifelong-mapping/)，被他带偏了.文章中提到“通过这种方法我们完全了新建完全子图中的 11 个边的计算”，所以我比较疑惑，为什么是11个边，在边缘化后新约束与旧约束不是已经包含在一起了么，看了原始PPT后才发现，PPT中压根没提11个边。实际上在对margin后的相关量进行稀疏化就是使用的 x2,x3,x4,x5,x8,x10几个状态量以及相应的9个边。那就没什么疑问了，感谢博主回复。
